// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolfpack.Data.Database;

#nullable disable

namespace Wolfpack.Data.Database.Migrations
{
    [DbContext(typeof(WolfpackContext))]
    [Migration("20220408092411_AddWolfEntityAndChangePackEntity")]
    partial class AddWolfEntityAndChangePackEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PackWolf", b =>
                {
                    b.Property<Guid>("PacksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WolvesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PacksId", "WolvesId");

                    b.HasIndex("WolvesId");

                    b.ToTable("PackWolf");
                });

            modelBuilder.Entity("Wolfpack.Data.Database.Entities.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("Wolfpack.Data.Database.Entities.Wolf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wolves");
                });

            modelBuilder.Entity("PackWolf", b =>
                {
                    b.HasOne("Wolfpack.Data.Database.Entities.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wolfpack.Data.Database.Entities.Wolf", null)
                        .WithMany()
                        .HasForeignKey("WolvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
